import {createTheme} from '@rneui/themed';

export const mainTheme = createTheme({
  lightColors: {
    primary: '#7762f6',
    // secondary: 'black',
    // background: 'black',
    // white: 'black',
    // black: 'black',
    // grey0: 'black',
    // grey1: 'black',
    // grey2: 'black',
    // grey3: 'black',
    // grey4: 'black',
    // grey5: 'black',
    // greyOutline: 'black',
    // searchBg: 'black',
    // success: 'black',
    // warning: 'black',
    // error: 'black',
    // disabled: 'black',
    // divider: 'black',
  },
  darkColors: {
    primary: 'black',
    // secondary: 'black',
    // background: 'black',
    // white: 'black',
    // black: 'black',
    // grey0: 'black',
    // grey1: 'black',
    // grey2: 'black',
    // grey3: 'black',
    // grey4: 'black',
    // grey5: 'black',
    // greyOutline: 'black',
    // searchBg: 'black',
    // success: 'black',
    // warning: 'black',
    // error: 'black',
    // disabled: 'black',
    // divider: 'black',
  },
  components: {
    Button: {
      // raised: true,
    },
  },
});
